# Generated by Django 5.2.1 on 2025-05-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_avaliacaotipo_turma_turnos_disciplina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Pessoa por Turma',
                'verbose_name_plural': 'Pessoas por Turma',
            },
        ),
    ]
