# Generated by Django 5.2.1 on 2025-05-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pessoaturma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areasaber',
            options={},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='avaliacaotipo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cursodisciplina',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={},
        ),
        migrations.AlterModelOptions(
            name='frequencia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='instituicaoensino',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ocupacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoaturma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='area_saber',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='area_saber',
        ),
        migrations.AddField(
            model_name='curso',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.areasaber'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.areasaber'),
        ),
        migrations.AlterField(
            model_name='areasaber',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.avaliacaotipo'),
        ),
        migrations.AlterField(
            model_name='avaliacaotipo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracao_meses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='carga_horaria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='periodo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='numero_faltas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_previsao_termino',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
        migrations.AlterField(
            model_name='ocupacao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nasc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ocupacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoaturma',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoaturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
