# Generated by Django 5.2.1 on 2025-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_areasaber_options_alter_avaliacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoaturma',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='pessoaturma',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='uf',
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='app.disciplina'),
        ),
        migrations.AddField(
            model_name='turma',
            name='pessoas',
            field=models.ManyToManyField(blank=True, to='app.pessoa'),
        ),
        migrations.DeleteModel(
            name='CursoDisciplina',
        ),
        migrations.DeleteModel(
            name='PessoaTurma',
        ),
    ]
