# Generated by Django 5.2.1 on 2025-05-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cidade_uf_cursodisciplina_pessoaturma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='disciplinas',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='pessoas',
        ),
    ]
