# Generated by Django 5.2.1 on 2025-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_curso_disciplinas_remove_turma_pessoas'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(through='app.CursoDisciplina', to='app.disciplina'),
        ),
        migrations.AddField(
            model_name='turma',
            name='pessoas',
            field=models.ManyToManyField(through='app.PessoaTurma', to='app.pessoa'),
        ),
    ]
